##
#' @title getModel
#'
#' @description Estimate a single partial MI model with a given anchor item set (aka cluster).
#'
#' @param res_testMI Object generated by \code{\link{testMI}}.
#' @param factor String, factor name.
#' @param which String, which MI level? Either \code{configural}
#' , \code{weak}
#' , \code{strong}
#' , or \code{strict}.
#' @param silent Do not print output? Defaults to \code{FALSE}.
#'
#' @return A single (multidimensional) model as defined by the \code{model}
#' argument in \code{testMI}. Results are directly printed to the console but can
#' be further inspected by lavaan's or mirt's functions.
#'
#' @usage res <- getModel(res_testMI,
#'                        "Factor1",
#'                        "configural")
#'
#' @export


getModel <- function(res_testMI,
                     factor,
                     which,  # desired model: configural, weak, strong, strict
                     silent = FALSE) { # dont print output?
  res <- res_testMI

  if (!silent) {
    if (res$settings$dichModel == "factor") {      # lavaan
      summary(res[[factor]][[which]][[1]], fit.measures = TRUE)
    } else {                                       # mirt
      cat("mirt model estimates\n\n")
      header <- capture.output(show(res[[factor]][[which]][[1]]))
      header <- header[grep("Full-info", header):(length(header) - 2)]
      cat(paste(header, collapse = "\n"))
      cat("\n")
      if (res$settings$missings == "none") {
        print(t(round(M2(res[[factor]][[which]][[1]]), 3)))
      } else {
        cat("Further fit statistics could not be computed due to missing values. (Maydeu-Olivares & Joe, 2006)")
      }
      cat("\n\nParameter Estimates:\n\n")
      print(coef(res[[factor]][[which]][[1]], simplify = TRUE))
    }
  }
  invisible(res[[factor]][[which]][[1]])
}
