# Thu Sep 16 14:51:16 2021 ------------------------------

##
#' @title Print relative DIF matrices
#'
#' @description Printing relative DIF matrices for a single model or from multiple clustering steps.
#'
#' @param res Results generated by \code{\link{clusterItems}} or \code{\link{testMI}}.
#'
#' @return Relative DIF matrices for item loadings and difficulties.
#'
#' @usage printDIF(res_clusterItems)
#'
#' @export


############

printDIF <- function(res) {
  if (is.null(res$Factor$itemClustering)) {
    cat(paste("Relative DIF of loadings in configural model\n"))
    pkg <- ifelse(res$model$dichModel == "factor",
                  "lavaan", "mirt")
    drids <- getDrids(res[["Factor"]]$configural[[1]], pkg)
    print(drids$L)

    cat(paste("\nRelative DIF of difficulties in configural model (assuming weak MI)\n"))
    print(drids$A)
    cat(paste("\nUse clusterItems() for further info."))

  } else {
    cat(paste("Relative DIF of loadings in configural model, resulting in",
              max(res$Factor$itemClustering$clusterLStep$cluster),
              "cluster.\n"))
    print(res$Factor$itemClustering$clusterLStep$drids$L)

    for (k in 1:max(res$Factor$itemClustering$clusterLStep$cluster)) {
      cat(paste("\nRelative DIF of difficulties for loading cluster",
                k, "\n"))
      print(res$Factor$itemClustering$modelAStep[[k]]$drids$A)
    }
  }
}
